name: "Hello World"

on: [push]

jobs:
  sample:
    name: Hello world Job
    runs-on: ubuntu-latest
    steps:
      -  run: 
          echo "Hello world"
          num1=3  # ここで第一の数値を設定
          num2=5  # ここで第二の数値を設定
          sum=$(($num1 + $num2))
          diff=$(($num1 - $num2))
          echo "Sum: $sum"
          echo "Difference: $diff"